// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Models;

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200402083739_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi.Models.EmpLeave", b =>
                {
                    b.Property<int>("el_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("e_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("el_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("el_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("empId")
                        .HasColumnType("int");

                    b.Property<int?>("lveId")
                        .HasColumnType("int");

                    b.HasKey("el_id");

                    b.HasIndex("empId");

                    b.HasIndex("lveId");

                    b.ToTable("EmpLeaves");
                });

            modelBuilder.Entity("WebApi.Models.EmployeeDetails", b =>
                {
                    b.Property<int>("e_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("e_dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_doj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("e_salary")
                        .HasColumnType("int");

                    b.HasKey("e_id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("WebApi.Models.LeaveDetails", b =>
                {
                    b.Property<int>("l_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("l_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("no_of_days")
                        .HasColumnType("int");

                    b.HasKey("l_id");

                    b.ToTable("Leave");
                });

            modelBuilder.Entity("WebApi.Models.EmpLeave", b =>
                {
                    b.HasOne("WebApi.Models.EmployeeDetails", "Employee")
                        .WithMany()
                        .HasForeignKey("empId");

                    b.HasOne("WebApi.Models.LeaveDetails", "Leave")
                        .WithMany()
                        .HasForeignKey("lveId");
                });
#pragma warning restore 612, 618
        }
    }
}
